// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbvjxpamljdkrwekojjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZidmp4cGFtbGpka3J3ZWtvampzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjMwMDEsImV4cCI6MjA2NTUzOTAwMX0.ZZfty7baFSiJPEWkm8zIZ2-acHybqFgOyaNr4tI2FEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);